# Generated by Django 5.1.7 on 2025-04-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_order_remove_product_stock_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='Mercado Pago', max_length=50),
        ),
    ]
