# Generated by Django 5.1.7 on 2025-04-15 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_orderitem_price_at_time_alter_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_especial', models.BooleanField(default=False, verbose_name='Is Special')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_info', to='products.product')),
            ],
        ),
    ]
