# Generated by Django 5.1.7 on 2025-09-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_order_direction_order_city_order_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
